//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pellared.SalaryBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pellared.SalaryBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowej wypłaty.
        /// </summary>
        public static string AddingNewSalaryText {
            get {
                return ResourceManager.GetString("AddingNewSalaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek.
        /// </summary>
        public static string AgeText {
            get {
                return ResourceManager.GetString("AgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data urodzenia.
        /// </summary>
        public static string BirthDateText {
            get {
                return ResourceManager.GetString("BirthDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownik musi mieć co najmniej 18 lat..
        /// </summary>
        public static string ComplexBirthDateValidatationErrorText {
            get {
                return ResourceManager.GetString("ComplexBirthDateValidatationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie.
        /// </summary>
        public static string DeleteSalaryDialogTitle {
            get {
                return ResourceManager.GetString("DeleteSalaryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć {0} {1}?.
        /// </summary>
        public static string DeleteSalaryQuestion {
            get {
                return ResourceManager.GetString("DeleteSalaryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string DeleteSalaryText {
            get {
                return ResourceManager.GetString("DeleteSalaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string EditSalaryText {
            get {
                return ResourceManager.GetString("EditSalaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport.
        /// </summary>
        public static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportText {
            get {
                return ResourceManager.GetString("ImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię lub nazwisko nie mogą być puste.
        /// </summary>
        public static string NameValidationErrorText {
            get {
                return ResourceManager.GetString("NameValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki {0} (*.{1})|*.{1}|Pliki {2} (*.{3})|*.{3}|Wszystkie pliki (*.*)|*.*.
        /// </summary>
        public static string OpenFileDialogText {
            get {
                return ResourceManager.GetString("OpenFileDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole wymagane.
        /// </summary>
        public static string RequiredValidationRuleText {
            get {
                return ResourceManager.GetString("RequiredValidationRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książka zarobków.
        /// </summary>
        public static string SalaryBookTitle {
            get {
                return ResourceManager.GetString("SalaryBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarobki.
        /// </summary>
        public static string SalaryText {
            get {
                return ResourceManager.GetString("SalaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki {0} (*.{1})|*.{1}|Wszystkie pliki (*.*)|*.*.
        /// </summary>
        public static string SaveFileDialogText {
            get {
                return ResourceManager.GetString("SaveFileDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        public static string ShowSalaryText {
            get {
                return ResourceManager.GetString("ShowSalaryText", resourceCulture);
            }
        }
    }
}
